version: "3.4"

services:
  core-api-service:
    image: core.api.dev.image
    container_name: core.api.dev.container
    build:
      args:
        buildconfig: Debug
      context: .
      dockerfile: development.dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

      # The .net core base image used in the docker file, runs the app on port 80 by default
      # Force it to run on ports 5000 & 5001
      # Also we are specifying 0.0.0.0 instead of localhost
      # as the app crashes inside docker when used localhost.
      - ASPNETCORE_URLS=http://0.0.0.0:5000/;https://0.0.0.0:5001
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - "./:/src"
