version: "3.9"
services:
    web:
        image: "milosnikic/footballappapi:latest"
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04"
        environment:
            SA_PASSWORD: "pa55w0rd!"
            ACCEPT_EULA: "Y"
    ng:
        image: "milosnikic/footballappweb:latest"
        ports:
            - "4200:4200"
        depends_on:
            - web
